---
# tasks file for acl_directory

- name: "Drop ACL on '{{ directory }}'"
  tags: [ acl ]
  changed_when: false
  ansible.builtin.command:
    cmd: "setfacl -Rb '{{ directory }}'"

- name: "Drop to 'root:root rw-rw----' for clean slate on '{{ directory }}'"
  tags: [ acl ]
  ansible.builtin.file:
    path: "{{ directory }}"
    state: directory
    owner: root
    group: root
    mode: ug=rw,o=-

- name: "Set +X on '{{ directory }}'"
  tags: [ acl ]
  ansible.builtin.file:
    path: "{{ directory }}"
    state: directory
    owner: root
    group: root
    mode: ug+X

- name: "Set 'group:{{ group }}:rwX' ACL for group '{{ group }}' on '{{ directory }}'"  # noqa: name[template]
  tags: [ acl ]
  ansible.posix.acl:
    path: "{{ directory }}"
    entity: "{{ group }}"
    etype: group
    recalculate_mask: mask
    recursive: true
    permissions: rwX
    state: present

- name: Set 'default:group:"{{ group }}":rwX' ACL for group '"{{ group }}"' on '{{ directory }}'  # noqa: name[template]
  tags: [ acl ]
  ansible.posix.acl:
    path: "{{ directory }}"
    entity: "{{ group }}"
    etype: group
    default: true
    recursive: true
    permissions: rwX
    state: present
